version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts_dev
    ports:
      - "5432:5432"
    volumes:
      - posts-backend-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  posts-backend-data:
